services:
  mysql:
    image: 'mysql:latest'
    restart: always
    environment:
      - 'MYSQL_DATABASE=expenses'
      - 'MYSQL_ROOT_PASSWORD=password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./docker-sql:/docker-entrypoint-initdb.d
